<a href="https://colab.research.google.com/github/hadiahmed1/DeepLearningForCV_FCC/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf
import numpy as np
tesnsorflow_zero=tf.constant(4)
print(tesnsorflow_zero)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensorflow_1d=tf.constant([2,0,-1])
print(tensorflow_1d)

tf.Tensor([ 2  0 -1], shape=(3,), dtype=int32)


In [4]:
tensorflow_2d=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensorflow_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [3]:
tensorflow_3d=tf.constant([
    [[5,7,4],[3,6,-2],[6,-1,9]],

    [[-3,7,8],[2,-6,-9],[2,5,-7]],
])
print(tensorflow_3d)

tf.Tensor(
[[[ 5  7  4]
  [ 3  6 -2]
  [ 6 -1  9]]

 [[-3  7  8]
  [ 2 -6 -9]
  [ 2  5 -7]]], shape=(2, 3, 3), dtype=int32)


In [6]:
print(tensorflow_3d.shape)

(2, 3, 3)


In [8]:
tf_o=tf.constant([2.3,6.1,-1.2],dtype=tf.float16)
print(tf_o)
tf_casted=tf.cast(tf_o,dtype=tf.int16)
print(tf_casted)

tf.Tensor([ 2.3  6.1 -1.2], shape=(3,), dtype=float16)
tf.Tensor([ 2  6 -1], shape=(3,), dtype=int16)


In [11]:
np_array=np.array([1,2,3,4])
print(np_array)
converted_array=tf.convert_to_tensor(np_array)
print(converted_array)

[1 2 3 4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [19]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=np.float32,
    name=None
)
print(5*eye_tensor)

tf.Tensor(
[[[5. 0. 0. 0. 0.]
  [0. 5. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 5.]]

 [[5. 0. 0. 0. 0.]
  [0. 5. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 5.]]], shape=(2, 5, 5), dtype=float32)


In [21]:
tensor_fill=tf.fill([2,3,3],2)
print(tensor_fill)

tf.Tensor(
[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]], shape=(2, 3, 3), dtype=int32)
