<a href="https://colab.research.google.com/github/hadiahmed1/DeepLearningForCV_FCC/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics**

In [2]:
import tensorflow as tf
import numpy as np
tesnsorflow_zero=tf.constant(4)
print(tesnsorflow_zero)

tf.Tensor(4, shape=(), dtype=int32)


In [2]:
tensorflow_1d=tf.constant([2,0,-1])
print(tensorflow_1d)

tf.Tensor([ 2  0 -1], shape=(3,), dtype=int32)


In [3]:
tensorflow_2d=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [3,8,4]
])
print(tensorflow_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 8 4]], shape=(4, 3), dtype=int32)


In [4]:
tensorflow_3d=tf.constant([
    [[5,7,4],[3,6,-2],[6,-1,9]],

    [[-3,7,8],[2,-6,-9],[2,5,-7]],
])
print(tensorflow_3d)

tf.Tensor(
[[[ 5  7  4]
  [ 3  6 -2]
  [ 6 -1  9]]

 [[-3  7  8]
  [ 2 -6 -9]
  [ 2  5 -7]]], shape=(2, 3, 3), dtype=int32)


In [5]:
print(tensorflow_3d.shape)

(2, 3, 3)


In [6]:
tf_o=tf.constant([2.3,6.1,-1.2],dtype=tf.float16)
print(tf_o)
tf_casted=tf.cast(tf_o,dtype=tf.int16)
print(tf_casted)

tf.Tensor([ 2.3  6.1 -1.2], shape=(3,), dtype=float16)
tf.Tensor([ 2  6 -1], shape=(3,), dtype=int16)


In [7]:
np_array=np.array([1,2,3,4])
print(np_array)
converted_array=tf.convert_to_tensor(np_array)
print(converted_array)

[1 2 3 4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [8]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=np.float32,
    name=None
)
print(5*eye_tensor)

tf.Tensor(
[[[5. 0. 0. 0. 0.]
  [0. 5. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 5.]]

 [[5. 0. 0. 0. 0.]
  [0. 5. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 5.]]], shape=(2, 5, 5), dtype=float32)


In [9]:
tensor_fill=tf.fill([2,3,3],2)
print(tensor_fill)

tf.Tensor(
[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]], shape=(2, 3, 3), dtype=int32)


In [10]:
print(tf.size(tensorflow_3d))

tf.Tensor(18, shape=(), dtype=int32)


In [11]:
#creating random
random_tensor=tf.random.normal([4,5],mean=100,stddev=5)
print(random_tensor)

tf.Tensor(
[[101.00619   99.146255 105.078125  98.519264 104.704544]
 [103.98227   98.78619  106.09292  100.33026   94.42784 ]
 [100.5514    95.99427   96.22795  108.20205   97.92118 ]
 [ 91.81399  107.07594  101.13179   97.390976  94.68963 ]], shape=(4, 5), dtype=float32)


In [12]:
random2_tensor=tf.random.uniform(shape=[3,4],minval=2,maxval=5)
print(random2_tensor)

tf.Tensor(
[[3.5629158 2.7427082 3.028298  4.0462303]
 [2.9532537 4.902417  2.3488367 4.0681744]
 [2.973089  3.294817  4.0359163 2.2050772]], shape=(3, 4), dtype=float32)


In [13]:
#SEED
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))

tf.Tensor(
[[3.941]
 [2.34 ]
 [2.715]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[2.719 ]
 [0.5615]
 [3.838 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[0.2393]
 [0.2979]
 [4.176 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[3.121]
 [3.395]
 [1.782]], shape=(3, 1), dtype=float16)


In [14]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))

tf.Tensor(
[[3.941]
 [2.34 ]
 [2.715]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[2.719 ]
 [0.5615]
 [3.838 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[0.2393]
 [0.2979]
 [4.176 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[3.121]
 [3.395]
 [1.782]], shape=(3, 1), dtype=float16)


In [15]:
indexed_tensor=tf.constant([4,7,2,8,2,6,3,7,3,8,9,4,6])
print(indexed_tensor[0::-1])

tf.Tensor([4], shape=(1,), dtype=int32)


# Initialization and Casting and Indexing

---

In [15]:
indexed_t=tf.constant([3,7,2,9,12,5,5,8,3,2,3,7])
print(indexed_t[2:9:2])

tf.Tensor([ 2 12  5  3], shape=(4,), dtype=int32)


In [16]:
#Indexing 2D
print(tensorflow_2d)
print(tensorflow_2d[0:3,0:2])
#row 2
print(tensorflow_2d[2,:])
#collumn 2
print(tensorflow_2d[:,2-1])


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 8 4]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([2 5 8 8], shape=(4,), dtype=int32)


In [17]:
#Indexing 3D
tensor_3d=tf.constant([
    [[5,7,4],[3,6,-2],[6,-1,9]],
    [[-3,7,8],[2,-6,-9],[2,5,-7]],
    [[-3,8,1],[6,-2,9],[13,4,8]],
    [[-4,8,-1],[-2,3,1],[24,2,6]]
])
print(tensor_3d)

tf.Tensor(
[[[ 5  7  4]
  [ 3  6 -2]
  [ 6 -1  9]]

 [[-3  7  8]
  [ 2 -6 -9]
  [ 2  5 -7]]

 [[-3  8  1]
  [ 6 -2  9]
  [13  4  8]]

 [[-4  8 -1]
  [-2  3  1]
  [24  2  6]]], shape=(4, 3, 3), dtype=int32)


In [19]:
print(tensor_3d[1:4,1:2,1:3])

tf.Tensor(
[[[-6 -9]]

 [[-2  9]]

 [[ 3  1]]], shape=(3, 1, 2), dtype=int32)


In [22]:
tensor_float=tf.constant([
    [4.8,7.3,7.2],
    [9.4,-3.27,3.6],
    [4.9,-2.766,-4.6]
]
)
print(tf.math.abs(tensor_float))

tf.Tensor(
[[4.8   7.3   7.2  ]
 [9.4   3.27  3.6  ]
 [4.9   2.766 4.6  ]], shape=(3, 3), dtype=float32)


In [24]:
#complex number
t_complex=tf.constant([[3-5j],[-12+5j],[4+5j]])
print(t_complex)
print(tf.abs(t_complex))

tf.Tensor(
[[  3.-5.j]
 [-12.+5.j]
 [  4.+5.j]], shape=(3, 1), dtype=complex128)
tf.Tensor(
[[ 5.83095189]
 [13.        ]
 [ 6.40312424]], shape=(3, 1), dtype=float64)


# Linear Algebra & Common Tensorflow Functions

---



In [9]:
m1=tf.constant([
    [1,-2],
    [-3,4],
    [3,1]])
m2=tf.constant([
    [3,-2,2],
    [4,3,-2]])
print(tf.linalg.matmul(m1,m2))

tf.Tensor(
[[ -5  -8   6]
 [  7  18 -14]
 [ 13  -3   4]], shape=(3, 3), dtype=int32)
