<a href="https://colab.research.google.com/github/hadiahmed1/DeepLearningForCV_FCC/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics**

In [1]:
import tensorflow as tf
import numpy as np
tesnsorflow_zero=tf.constant(4)
print(tesnsorflow_zero)

tf.Tensor(4, shape=(), dtype=int32)


In [2]:
tensorflow_1d=tf.constant([2,0,-1])
print(tensorflow_1d)

tf.Tensor([ 2  0 -1], shape=(3,), dtype=int32)


In [3]:
tensorflow_2d=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [3,8,4]
])
print(tensorflow_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 8 4]], shape=(4, 3), dtype=int32)


In [4]:
tensorflow_3d=tf.constant([
    [[5,7,4],[3,6,-2],[6,-1,9]],

    [[-3,7,8],[2,-6,-9],[2,5,-7]],
])
print(tensorflow_3d)

tf.Tensor(
[[[ 5  7  4]
  [ 3  6 -2]
  [ 6 -1  9]]

 [[-3  7  8]
  [ 2 -6 -9]
  [ 2  5 -7]]], shape=(2, 3, 3), dtype=int32)


In [5]:
print(tensorflow_3d.shape)

(2, 3, 3)


In [6]:
tf_o=tf.constant([2.3,6.1,-1.2],dtype=tf.float16)
print(tf_o)
tf_casted=tf.cast(tf_o,dtype=tf.int16)
print(tf_casted)

tf.Tensor([ 2.3  6.1 -1.2], shape=(3,), dtype=float16)
tf.Tensor([ 2  6 -1], shape=(3,), dtype=int16)


In [7]:
np_array=np.array([1,2,3,4])
print(np_array)
converted_array=tf.convert_to_tensor(np_array)
print(converted_array)

[1 2 3 4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [8]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=np.float32,
    name=None
)
print(5*eye_tensor)

tf.Tensor(
[[[5. 0. 0. 0. 0.]
  [0. 5. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 5.]]

 [[5. 0. 0. 0. 0.]
  [0. 5. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 5.]]], shape=(2, 5, 5), dtype=float32)


In [9]:
tensor_fill=tf.fill([2,3,3],2)
print(tensor_fill)

tf.Tensor(
[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]], shape=(2, 3, 3), dtype=int32)


In [10]:
print(tf.size(tensorflow_3d))

tf.Tensor(18, shape=(), dtype=int32)


In [11]:
#creating random
random_tensor=tf.random.normal([4,5],mean=100,stddev=5)
print(random_tensor)

tf.Tensor(
[[ 97.0617    99.355415  90.50922   96.433624  94.306335]
 [ 99.75355   94.32118  104.10032   93.80178  102.796104]
 [102.66948   95.51867  102.447365  97.80032   96.1574  ]
 [109.73501  103.80182  103.70466  112.234924  97.15191 ]], shape=(4, 5), dtype=float32)


In [12]:
random2_tensor=tf.random.uniform(shape=[3,4],minval=2,maxval=5)
print(random2_tensor)

tf.Tensor(
[[2.5370765 3.0689812 3.2153068 2.978519 ]
 [4.620905  4.4678965 4.6423798 3.1808949]
 [2.7039304 3.3813415 2.2149062 3.7848613]], shape=(3, 4), dtype=float32)


In [13]:
#SEED
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))

tf.Tensor(
[[3.941]
 [2.34 ]
 [2.715]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[2.719 ]
 [0.5615]
 [3.838 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[0.2393]
 [0.2979]
 [4.176 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[3.121]
 [3.395]
 [1.782]], shape=(3, 1), dtype=float16)


In [14]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))

tf.Tensor(
[[3.941]
 [2.34 ]
 [2.715]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[2.719 ]
 [0.5615]
 [3.838 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[0.2393]
 [0.2979]
 [4.176 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[3.121]
 [3.395]
 [1.782]], shape=(3, 1), dtype=float16)


In [15]:
indexed_tensor=tf.constant([4,7,2,8,2,6,3,7,3,8,9,4,6])
print(indexed_tensor[0::-1])

tf.Tensor([4], shape=(1,), dtype=int32)


# Initialization and Casting and Indexing

---

In [22]:
indexed_t=tf.constant([3,7,2,9,12,5,5,8,3,2,3,7])
print(indexed_t[2:9:2])

tf.Tensor([ 2 12  5  3], shape=(4,), dtype=int32)


In [23]:
#Indexing 2D
print(tensorflow_2d)
print(tensorflow_2d[0:3,0:2])
#row 2
print(tensorflow_2d[2,:])
#collumn 2
print(tensorflow_2d[:,2-1])


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 8 4]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([2 5 8 8], shape=(4,), dtype=int32)


In [24]:
#Indexing 3D
tensor_3d=tf.constant([
    [[5,7,4],[3,6,-2],[6,-1,9]],
    [[-3,7,8],[2,-6,-9],[2,5,-7]],
    [[-3,8,1],[6,-2,9],[13,4,8]],
    [[-4,8,-1],[-2,3,1],[24,2,6]]
])
print(tensor_3d)

tf.Tensor(
[[[ 5  7  4]
  [ 3  6 -2]
  [ 6 -1  9]]

 [[-3  7  8]
  [ 2 -6 -9]
  [ 2  5 -7]]

 [[-3  8  1]
  [ 6 -2  9]
  [13  4  8]]

 [[-4  8 -1]
  [-2  3  1]
  [24  2  6]]], shape=(4, 3, 3), dtype=int32)


In [25]:
print(tensor_3d[1:4,1:2,1:3])

tf.Tensor(
[[[-6 -9]]

 [[-2  9]]

 [[ 3  1]]], shape=(3, 1, 2), dtype=int32)


In [26]:
tensor_float=tf.constant([
    [4.8,7.3,7.2],
    [9.4,-3.27,3.6],
    [4.9,-2.766,-4.6]
]
)
print(tf.math.abs(tensor_float))

tf.Tensor(
[[4.8   7.3   7.2  ]
 [9.4   3.27  3.6  ]
 [4.9   2.766 4.6  ]], shape=(3, 3), dtype=float32)


In [27]:
#complex number
t_complex=tf.constant([[3-5j],[-12+5j],[4+5j]])
print(t_complex)
print(tf.abs(t_complex))

tf.Tensor(
[[  3.-5.j]
 [-12.+5.j]
 [  4.+5.j]], shape=(3, 1), dtype=complex128)
tf.Tensor(
[[ 5.83095189]
 [13.        ]
 [ 6.40312424]], shape=(3, 1), dtype=float64)


# Linear Algebra & Common Tensorflow Functions

---



In [28]:
m1=tf.constant([
    [1,-2],
    [-3,4],
    [3,1]])
m2=tf.constant([
    [3,-2,2],
    [4,3,-2]])
print(tf.linalg.matmul(m1,m2))

tf.Tensor(
[[ -5  -8   6]
 [  7  18 -14]
 [ 13  -3   4]], shape=(3, 3), dtype=int32)


#CommonTensorFlow Functions

In [29]:
tensor_3d=tf.constant([
    [[5,7,4],[3,6,-2],[6,-1,9]],
    [[-3,7,8],[2,-6,-9],[2,5,-7]],
    [[-3,8,1],[6,-2,9],[13,4,8]],
    [[-4,8,-1],[-2,3,1],[24,2,6]]
])
print(tensor_3d.shape)
print(tf.expand_dims(tensor_3d,axis=0))

(4, 3, 3)
tf.Tensor(
[[[[ 5  7  4]
   [ 3  6 -2]
   [ 6 -1  9]]

  [[-3  7  8]
   [ 2 -6 -9]
   [ 2  5 -7]]

  [[-3  8  1]
   [ 6 -2  9]
   [13  4  8]]

  [[-4  8 -1]
   [-2  3  1]
   [24  2  6]]]], shape=(1, 4, 3, 3), dtype=int32)


In [30]:
x=tf.constant([[[2,3,4,5],[5,7,8,9]]])
x_squeezed=tf.squeeze(x,axis=0)
x_squeezed

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [5, 7, 8, 9]], dtype=int32)>

In [31]:
tf.reshape(x,[4,-1])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [5, 7],
       [8, 9]], dtype=int32)>

In [32]:
c1=tf.constant([
    [1,2,3],
     [4,5,6]])
c2=tf.constant([
    [7,8,9],
     [-1,-2,-3]])
tf.concat([c1,c2],1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, -1, -2, -3]], dtype=int32)>

In [33]:
tf.stack([c1,c2],0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [-1, -2, -3]]], dtype=int32)>

In [34]:
tf.pad(c1,[[1,2],[3,4]],constant_values=0,)

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [35]:
p=tf.constant([['p1','p2','p3','p4','p5','p6','p7'],
               ['p-1','p-2','p-3','p-4','p-5','p-6','p-7'],
               ['p+1','p+2','p+3','p+4','p+5','p+6','p+7']])
tf.gather(p,[2,0])
tf.gather(p,[3,6],axis=1)

<tf.Tensor: shape=(3, 2), dtype=string, numpy=
array([[b'p4', b'p7'],
       [b'p-4', b'p-7'],
       [b'p+4', b'p+7']], dtype=object)>

In [36]:
tf.gather_nd(p,[[1,4],[0,2],[2,6],[1,5]])

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'p-5', b'p3', b'p+7', b'p-6'], dtype=object)>

# Ragged Tensor

In [49]:
tensor_2d=tf.constant([[1,5,7],
                  [8,2,9],
                  [6,6,1],
                  [2,8,5]])
tensor_2d.shape

TensorShape([4, 3])

In [41]:
t_2d=[[1,5,7],
      [8,2],
      [6,6,1,7],
      [2,8,5]]
t_ragged=tf.ragged.constant(t_2d)
t_ragged.shape

TensorShape([4, None])

In [47]:
value=[4,7,2,9,1,4,6,7,3,2,5,9,3]
row_length=[6,3,0,4]
limit=[4,6,6,9,13]
tf.RaggedTensor.from_row_lengths(values=value,row_lengths=row_length)
tf.RaggedTensor.from_row_limits(value,limit)

<tf.RaggedTensor [[4, 7, 2, 9], [1, 4], [], [6, 7, 3], [2, 5, 9, 3]]>

In [50]:
tf.RaggedTensor.from_tensor(tensor_2d,lengths=[3,2,0,1])

<tf.RaggedTensor [[1, 5, 7], [8, 2], [], [2]]>

# Sparse Tensor

In [52]:
tensor_sparse=tf.sparse.SparseTensor(indices=[[2,3],[3,4]],values=[4,7],dense_shape=[5,6])
print(tensor_sparse)
print(tf.sparse.to_dense(tensor_sparse))

SparseTensor(indices=tf.Tensor(
[[2 3]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([4 7], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))
tf.Tensor(
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 7 0]
 [0 0 0 0 0 0]], shape=(5, 6), dtype=int32)


# Variable Tensors

In [54]:
x=tf.constant([3,6])
x_var=tf.Variable(x,name="var")
print(x_var)

<tf.Variable 'var:0' shape=(2,) dtype=int32, numpy=array([3, 6], dtype=int32)>


In [55]:
x_var.assign_add([2,7])
x_var

<tf.Variable 'var:0' shape=(2,) dtype=int32, numpy=array([ 5, 13], dtype=int32)>