<a href="https://colab.research.google.com/github/hadiahmed1/DeepLearningForCV_FCC/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics**

In [1]:
import tensorflow as tf
import numpy as np
tesnsorflow_zero=tf.constant(4)
print(tesnsorflow_zero)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensorflow_1d=tf.constant([2,0,-1])
print(tensorflow_1d)

tf.Tensor([ 2  0 -1], shape=(3,), dtype=int32)


In [4]:
tensorflow_2d=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensorflow_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [2]:
tensorflow_3d=tf.constant([
    [[5,7,4],[3,6,-2],[6,-1,9]],

    [[-3,7,8],[2,-6,-9],[2,5,-7]],
])
print(tensorflow_3d)

tf.Tensor(
[[[ 5  7  4]
  [ 3  6 -2]
  [ 6 -1  9]]

 [[-3  7  8]
  [ 2 -6 -9]
  [ 2  5 -7]]], shape=(2, 3, 3), dtype=int32)


In [6]:
print(tensorflow_3d.shape)

(2, 3, 3)


In [8]:
tf_o=tf.constant([2.3,6.1,-1.2],dtype=tf.float16)
print(tf_o)
tf_casted=tf.cast(tf_o,dtype=tf.int16)
print(tf_casted)

tf.Tensor([ 2.3  6.1 -1.2], shape=(3,), dtype=float16)
tf.Tensor([ 2  6 -1], shape=(3,), dtype=int16)


In [11]:
np_array=np.array([1,2,3,4])
print(np_array)
converted_array=tf.convert_to_tensor(np_array)
print(converted_array)

[1 2 3 4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [19]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=np.float32,
    name=None
)
print(5*eye_tensor)

tf.Tensor(
[[[5. 0. 0. 0. 0.]
  [0. 5. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 5.]]

 [[5. 0. 0. 0. 0.]
  [0. 5. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 5.]]], shape=(2, 5, 5), dtype=float32)


In [21]:
tensor_fill=tf.fill([2,3,3],2)
print(tensor_fill)

tf.Tensor(
[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]], shape=(2, 3, 3), dtype=int32)


In [3]:
print(tf.size(tensorflow_3d))

tf.Tensor(18, shape=(), dtype=int32)


In [7]:
#creating random
random_tensor=tf.random.normal([4,5],mean=100,stddev=5)
print(random_tensor)

tf.Tensor(
[[101.519775 101.25927  100.609436 109.8098   104.81389 ]
 [ 99.490814 104.07106   96.44186  107.29775  101.752426]
 [ 95.39298  101.38784   99.34694  102.19481  102.78859 ]
 [ 93.2788    99.30835  102.007     96.404106  95.82303 ]], shape=(4, 5), dtype=float32)


In [8]:
random2_tensor=tf.random.uniform(shape=[3,4],minval=2,maxval=5)
print(random2_tensor)

tf.Tensor(
[[3.5100884 4.327753  2.2757592 2.3195324]
 [3.2600918 4.638008  2.9189227 3.2364018]
 [2.181547  3.7433968 2.1048336 2.0540824]], shape=(3, 4), dtype=float32)


In [9]:
#SEED
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))

tf.Tensor(
[[3.941]
 [2.34 ]
 [2.715]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[2.719 ]
 [0.5615]
 [3.838 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[0.2393]
 [0.2979]
 [4.176 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[3.121]
 [3.395]
 [1.782]], shape=(3, 1), dtype=float16)


In [10]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))
print(tf.random.uniform(shape=[3,1],maxval=5,dtype=tf.float16,seed=10))

tf.Tensor(
[[3.941]
 [2.34 ]
 [2.715]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[2.719 ]
 [0.5615]
 [3.838 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[0.2393]
 [0.2979]
 [4.176 ]], shape=(3, 1), dtype=float16)
tf.Tensor(
[[3.121]
 [3.395]
 [1.782]], shape=(3, 1), dtype=float16)
